service: transaction-serverless

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1

functions:
  transaction:
    handler: handler.transaction
    events:
      - sns: arn:aws:sns:ap-southeast-1:156969275739:create_transaction
